POST http://localhost:8080/register
Content-Type: application/json

{
  "id": 0,
  "periodo": "2020",
  "ciclo": "4",
  "horasCumplidas": 12,
  "prioridad": true,
  "idEstudiante": 2,
  "usuario": {
    "id": 0,
    "cedula": "1724455211",
    "nombre": "Andres",
    "apellido": "Zuin",
    "correo": "andres@gmail.com",
    "titulo": "BGU",
    "telefono": "0928374321",
    "activo": true,
    "password": "1234"
  }
}

###



